<a href="https://colab.research.google.com/github/alexgar76/Curso_Ciencia_Datos/blob/main/Manipulacion_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#Cambio de forma en Array (reshape)
import numpy as np

arr= np.arange(12) #Crea un array de 0 a 11
print(arr)
reshape_arr=arr.reshape(3,4) #Lo transforma en una matriz de 3x4
print(reshape_arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
#Aplanamiento de Arrays(Flatten y Ravel)
import numpy as np
flattened_arr=reshape_arr.flatten() #Lo transforma en un array de 1 dimensión
print(flattened_arr)
raveled_arr=reshape_arr.ravel() #Aplanar el arrar manteniendo la vista original, si es posible
print(raveled_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
#Concatenacion de Array
arr1=np.array([[1,2],[3,4]])
#print(arr1)
arr2=np.array([[5,6],[7,8]])
#print(arr2)
concatened_arr=np.concatenate((arr1,arr2),axis=0) #Concatenar a lo largo del eje 0
print(concatened_arr)
raveled_arr1=concatened_arr.ravel()
print(raveled_arr1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6 7 8]


In [34]:
#Division de Array
arr=np.arange(9)
print(arr)
split_arr=np.split(arr,3) #Dividir el array en 3 partes
print(split_arr)

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
