<a href="https://colab.research.google.com/github/alexgar76/Curso_Ciencia_Datos/blob/main/Operaciones_Aritmeticas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
#suma, resta, multiplicacion y division de arrays
sum_arr = arr1 + arr2
diff_arr = arr1 - arr2
mult_arr = arr1 * arr2
div_arr =arr1 / arr2
print(sum_arr)
print(diff_arr)
print(mult_arr)
print(div_arr)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [3]:
#funciones universale (ufuncs)


arr = np.array([0,np.pi/2,np.pi])
print(arr)
sin_arr = np.sin(arr)
cos_arr = np.cos(arr)
exp_arr = np.exp(arr)
log_arr = np.log(arr+1) #evitar log (0) que serultaria en  -inf
tan_arr = np.tan(arr)

print(sin_arr)
print(cos_arr)
print(exp_arr)
print(log_arr)
print(tan_arr)

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 1.          4.81047738 23.14069263]
[0.         0.94421571 1.42108041]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [4]:
#operaciones de algebra lineal
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
#multiplicacion de matrices
mat_mult = np.dot(matrix1,matrix2)
print(mat_mult)


[[19 22]
 [43 50]]
